name: Build & Push Docker image to DockerHub

on:
  push:
    branches:
      - master
      
permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Docker tag automatically
        id: vars
        run: |
          git fetch --tags
          LAST_TAG=$(git tag --sort=-v:refname | head -n 1)
          BASE="1.0."
          COUNT=$((${LAST_TAG##*.}+1))
          VERSION="${BASE}${COUNT}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Next Docker tag: $VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vps-saas-deployer:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/vps-saas-deployer:${{ steps.vars.outputs.version }}

      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.vars.outputs.version }}
          git push origin ${{ steps.vars.outputs.version }}